MBLBundle\Entity\Chat:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }

    manyToMany:
        msgs:
            targetEntity: MBLBundle\Entity\Text
            inversedBy: chats