MBLBundle\Entity\Chat:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        dateCreation:
            type: date

    lifecycleCallbacks: {  }

    manyToMany:
        msgs:
            targetEntity: MBLBundle\Entity\Text
            inversedBy: chats
            cascade: ["persist"]

        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: chats
            cascade: ["persist"]


