MBLBundle\Entity\Chat:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name_fr:
            type: string
            length: 255
            nullable: true
        name_it:
            type: string
            length: 255
            nullable: true
        dateCreation_fr:
            type: date
        dateCreation_it:
            type: date
        connectionbyidcreator_fr:
            type: integer
            nullable: true
        connectionbyidcreator_it:
            type: integer
            nullable: true
        connectionbyid_fr:
            type: integer
            nullable: true
        connectionbyid_it:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }

    manyToMany:
        msgs:
            targetEntity: MBLBundle\Entity\Text
            inversedBy: chats
            cascade: ["persist"]

        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: chats
            cascade: ["persist"]

#    oneToOne:
#        userCreator:
#            targetEntity: MBLBundle\Entity\Profil
#        userCall:
#            targetEntity: MBLBundle\Entity\Profil
#



