MBLBundle\Entity\Competences:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\CompetencesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        competencesFr:
            type: string
            length: 255
        competencesIt:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToMany:
        profilsrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: competences

        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: competences