MBLBundle\Entity\Competences:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\CompetencesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        competences:
            type: string
            length: 255
    lifecycleCallbacks: {  }
