MBLBundle\Entity\Dispo:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\DispoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dispo_fr:
            type: string
            length: 255
        dispo_it:
            type: string
            length: 255
    lifecycleCallbacks: {  }


    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: dispo

        profilrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: dispo