MBLBundle\Entity\Dispo:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\DispoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dispo:
            type: string
            length: 255
    lifecycleCallbacks: {  }


    oneToOne:
        profilrecherche:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: dispo

    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: dispo