MBLBundle\Entity\ETQ:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ETQRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        etq:
            type: string
            length: 255
    lifecycleCallbacks: {  }


    oneToOne:
        profilrecherche:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: etq


    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: etq