MBLBundle\Entity\Invest:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\InvestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        investFr:
            type: string
            length: 255
        investIt:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    oneToOne:
        profil:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: invest

    oneToMany:
        profilrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: invest

