MBLBundle\Entity\Invest:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\InvestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        invest:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    oneToOne:
        profilrecherche:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: invest

        profil:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: invest

