MBLBundle\Entity\Metier:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\MetierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        metier:
            type: string
            length: 255
    lifecycleCallbacks: {  }


    oneToOne:
        profilrecherche:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: metier

    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: metier
