MBLBundle\Entity\Metier:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\MetierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        metierfr:
            type: string
            length: 255
        metierit:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: metier

        profilrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: metier
