MBLBundle\Entity\Ou:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\OuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ou:
            type: string
            length: 255
    lifecycleCallbacks: {  }



    oneToOne:
        profilrecherche:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: ou


    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: ou