MBLBundle\Entity\Ou:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\OuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ouFr:
            type: string
            length: 255
        ouIt:
            type: string
            length: 255
    lifecycleCallbacks: {  }



    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: ou

        profilrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: ou