MBLBundle\Entity\Profil:
    type: entity
    table: fos_user
    repositoryClass: MBLBundle\Repository\ProfilRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nomFr:
            type: string
            length: 255
            nullable: true
        nomIt:
            type: string
            length: 255
            nullable: true
        prenomFr:
            type: string
            length: 255
            nullable: true
        prenomIt:
            type: string
            length: 255
            nullable: true
        descriptionFr:
            type: text
            nullable: true
        descriptionIt:
            type: text
            nullable: true
        linkedInFr:
            type: string
            length: 255
            nullable: true
        linkedInIt:
            type: string
            length: 255
            nullable: true
        localisationFr:
            type: string
            length: 255
            nullable: true
        localisationIt:
            type: string
            length: 255
            nullable: true


    lifecycleCallbacks: {  }


    manyToOne:
        etq:
            targetEntity: MBLBundle\Entity\ETQ
            inversedBy: profils

        dispo:
            targetEntity: MBLBundle\Entity\Dispo
            inversedBy: profils

        ou:
            targetEntity: MBLBundle\Entity\Ou
            inversedBy: profils

        metier:
            targetEntity: MBLBundle\Entity\Metier
            inversedBy: profils



    manyToMany:
        competences:
            targetEntity: MBLBundle\Entity\Competences
            inversedBy: profils
        projets:
            targetEntity: MBLBundle\Entity\Projet
            inversedBy: profils
            cascade: ["persist"]
        chats:
            targetEntity: MBLBundle\Entity\Chat
            inversedBy: profils
            cascade: ["persist"]


    oneToOne:
        invest:
            targetEntity: MBLBundle\Entity\Invest
            inversedBy: profil

        fichier:
            targetEntity: MBLBundle\Entity\Fichier
            cascade: ['all']