MBLBundle\Entity\ProfilRecherche:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ProfilRechercheRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO




    manyToMany:
        projets:
            targetEntity: MBLBundle\Entity\Projet
            mappedBy: profilsrecherches
            cascade: ["all"]

        competences:
            targetEntity: MBLBundle\Entity\Competences
            inversedBy: profilsrecherches


    manyToOne:
        etq:
            targetEntity: MBLBundle\Entity\ETQ
            inversedBy: profilrecherches

        ou:
            targetEntity: MBLBundle\Entity\Ou
            inversedBy: profilrecherches

        invest:
            targetEntity: MBLBundle\Entity\Invest
            inversedBy: profilrecherches

        dispo:
            targetEntity: MBLBundle\Entity\Dispo
            inversedBy: profilrecherches

        metier:
            targetEntity: MBLBundle\Entity\Metier
            inversedBy: profilrecherches