MBLBundle\Entity\ProfilRecherche:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ProfilRechercheRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    manyToMany:
        projets:
            targetEntity: MBLBundle\Entity\Projet
            mappedBy: profilsrecherches

        competences:
            targetEntity: MBLBundle\Entity\Competences
            inversedBy: profilsrecherches


    oneToOne:
        etq:
            targetEntity: MBLBundle\Entity\ETQ
            inversedBy: profilrecherche

        ou:
            targetEntity: MBLBundle\Entity\Ou
            inversedBy: profilrecherche

        invest:
            targetEntity: MBLBundle\Entity\Invest
            inversedBy: profilrecherche

        dispo:
            targetEntity: MBLBundle\Entity\Dispo
            inversedBy: profilrecherche

        metier:
            targetEntity: MBLBundle\Entity\Metier
            inversedBy: profilrecherche