MBLBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titrefr:
            type: string
            length: 255
            nullable: true
        titreit:
            type: string
            length: 255
            nullable: true
        descriptionfr:
            type: text
            nullable: true
        descriptionit:
            type: text
            nullable: true
        siteInternetfr:
            type: string
            length: 255
            nullable: true
        siteInternetit:
            type: string
            length: 255
            nullable: true
        ebustaUrlfr:
            type: string
            length: 255
            nullable: true
        ebustaUrlit:
            type: string
            length: 255
            nullable: true
        localisationfr:
            type: string
            length: 255
            nullable: true
        localisationit:
            type: string
            length: 255
            nullable: true
        dateCreation:
            type: datetime



    lifecycleCallbacks: {  }

    manyToOne:
        secteur:
            targetEntity: MBLBundle\Entity\Secteur
            inversedBy: projets
            cascade: ["persist"]

        fichier:
            targetEntity: MBLBundle\Entity\Fichier
            cascade: ['all']

        typeDeProjet:
            targetEntity: MBLBundle\Entity\TypeDeProjet
            inversedBy: projets
            cascade: ["persist"]
    manyToMany:
        profilsrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            inversedBy: projets
            cascade: ["persist"]

        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: projets
            cascade: ["persist"]