MBLBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        description:
            type: text
        siteInternet:
            type: string
            length: 255
            nullable: true
        ebustaUrl:
            type: string
            length: 255
            nullable: true
        localisation:
            type: string
            length: 255
        dateCreation:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        secteur:
            targetEntity: MBLBundle\Entity\Secteur
            inversedBy: projets

        typeDeProjet:
            targetEntity: MBLBundle\Entity\TypeDeProjet
            inversedBy: projets

        matching:
            targetEntity: MBLBundle\Entity\Matching


    oneToMany:
        fichiers:
            targetEntity: MBLBundle\Entity\Fichier



    manyToMany:
        profilRecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            inversedBy: projets