MBLBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreFr:
            type: string
            length: 255
        titreIt:
            type: string
            length: 255
        description_fr:
            type: text
        description_it:
            type: text
        siteInternet_fr:
            type: string
            length: 255
        siteInternet_it:
            type: string
            length: 255
            nullable: true
        ebustaUrl_fr:
            type: string
            length: 255
            nullable: true
        ebustaUrl_it:
            type: string
            length: 255
            nullable: true
        localisation_fr:
            type: string
            length: 255
        localisation_it:
            type: string
            length: 255
        dateCreation:
            type: datetime



    lifecycleCallbacks: {  }

    manyToOne:
        secteur:
            targetEntity: MBLBundle\Entity\Secteur
            inversedBy: projets
            cascade: ["persist"]

        fichier:
            targetEntity: MBLBundle\Entity\Fichier
            cascade: ['all']

        typeDeProjet:
            targetEntity: MBLBundle\Entity\TypeDeProjet
            inversedBy: projets
            cascade: ["persist"]
    manyToMany:
        profilsrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            inversedBy: projets
            cascade: ["persist"]

        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: projets
            cascade: ["persist"]