MBLBundle\Entity\Secteur:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\SecteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        secteurActiviteFr:
            type: string
            length: 255
        secteurActiviteIt:
            type: string
            length: 255

    lifecycleCallbacks: {  }

    oneToMany:
        projets:
            targetEntity: MBLBundle\Entity\Projet
            mappedBy: secteur
            cascade: ["persist"]