MBLBundle\Entity\Text:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\TextRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        msgFr:
            type: string
        msgIt:
            type: string
        datecreationFr:
            type: datetime
        datecreationIt:
            type: datetime
        profilFr:
            type: string
        profilIt:
            type: string

    lifecycleCallbacks: {  }


    manyToMany:
        chats:
            targetEntity: MBLBundle\Entity\Chat
            mappedBy: msgs
            cascade: ["persist"]
