MBLBundle\Entity\Text:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\TextRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        msg:
            type: string
        dateCreation:
            type: datetime
        profil:
            type: string
        seen:
            type: integer
            nullable: true


    lifecycleCallbacks: {  }


    manyToMany:
        chats:
            targetEntity: MBLBundle\Entity\Chat
            mappedBy: msgs
            cascade: ["persist"]
