MBLBundle\Entity\Text:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        msg:
            type: string
        datecreation:
            type: datetime
    lifecycleCallbacks: {  }



    manyToOne:
        profil:
            targetEntity: MBLBundle\Entity\Profil
            inversedBy: texts

    manyToMany:
        chats:
            targetEntity: MBLBundle\Entity\Chat
            mappedBy: msgs
