MBLBundle\Entity\Text:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\TextRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        msg_fr:
            type: string
        msg_it:
            type: string
        datecreation_fr:
            type: datetime
        datecreation_it:
            type: datetime
        profil_fr:
            type: string
        profil_it:
            type: string

    lifecycleCallbacks: {  }


    manyToMany:
        chats:
            targetEntity: MBLBundle\Entity\Chat
            mappedBy: msgs
            cascade: ["persist"]
