MBLBundle\Entity\Text:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: msg
        datecreation:
            type: datetime
    lifecycleCallbacks: {  }

    manyToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            inversedBy: msgs

        chats:
            targetEntity: MBLBundle\Entity\Chat
            mappedBy: msgs
