MBLBundle\Entity\TypeDeProjet:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\TypeDeProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeDeProjet_fr:
            type: string
            length: 255
        typeDeProjet_it:
            type: string
            length: 255


    lifecycleCallbacks: {  }

    oneToMany:
        projets:
            targetEntity: MBLBundle\Entity\Projet
            mappedBy: typeDeProjet
            cascade: ["persist"]