mbl:
    resource: "@MBLBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: it|fr
       #        _locale: fr|it

fos_user:
    resource: "@MBLBundle/Resources/config/routing/all.xml"

#    "@FOSUserBundle/Resources/config/routing/all.xml"
