# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    ###Fournisseur pour récupérer les utilisateurs###
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        ###Nom du parefeu, identifiant unique pouvant être nommé comme on le souhaite###
        main:
            ###Masque d'url, dans ce cas on définit que le parefeu main protège le site entier###
            pattern: ^/
            ###Méthode d'authenfication utilisé par ce parefeu
            form_login:
                ###Fournisseur d'utilisateurs que l'on retrouve quelques lignes plus haut###
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

                failure_path:   /
                failure_forward: false
                failure_path_parameter: _failure_path

            ###Autorise la deconnexion###
            logout: true

            ###Autorise les anonymes à naviguer###
            anonymous: true
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    ###Permet d'encoder les mdp###
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    ###Hiérarchie des rôles###
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    ###Contrôle d'accès aux pages###
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/createProject, role: ROLE_USER }
        - { path: ^/editProfil, role: ROLE_USER }
        - { path: ^/showMyProfil, role: ROLE_USER }
        - { path: ^/showMyProject, role: ROLE_USER }
        - { path: ^/connect, role: ROLE_USER }
        - { path: ^/homepageProfil, role: ROLE_USER }

