mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:Default:index }

mbl_addProjet:
    path:     /ajout-projet
    defaults: { _controller: MBLBundle:Default:addProjet }

mbl_addProfil:
    path:     /ajout-profil
    defaults: { _controller: MBLBundle:Default:addProfil }

userHomepage:
    path: /userHomepage
    defaults: { _controller: MBLBundle:Default:userHomepage }
