mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:User:index }

homepageProfil:
    path: /homepageProfil
    defaults: { _controller: MBLBundle:User:homepageProfil }

editProfil:
    path: /editProfil
    defaults: { _controller: MBLBundle:User:editProfil }

#deleteProfil:
#    path: /delete
#    defaults: { _controller: "MBLBundle:User:delete"}
#    methods:  DELETE

showProfil:
    path: /showProfil/{id}
    defaults: { _controller: MBLBundle:User:showProfil }

showMyProfil:
    path: /showMyProfil
    defaults: { _controller: MBLBundle:User:showMyProfil }

showAllProfils:
    path: /showAllProfils
    defaults: { _controller: MBLBundle:User:showAllProfils }

createProjet:
    path: /createProject
    defaults: { _controller: MBLBundle:User:createProject }

editProjet:
    path: /editProject/{id}
    defaults: { _controller: MBLBundle:User:editProject }

#Création, édition, delete PROFIL RECHERCHER
createProfilRechercheProjet:
    path: /createProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:createProfilRechercheProject
        id: null

newProfilRechercheProjet:
    path: /newProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:newProfilRechercheProject
        id: null

editProfilRechercheProjet:
    path: /editProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:editProfilRechercheProject
        id: null

deleteProfilRechercheProjet:
    path: /deleteProfilRecherche/{id}
    defaults:
        _controller: MBLBundle:User:deleteProfilRecherche


deleteProfilRerchercheProjet:
    path: /deleteProfil
    defaults: { _controller: MBLBundle:User:deleteProfilR}

showProject:
    path: /showProject
    defaults: { _controller: MBLBundle:User:showProject }

showOneProject:
    path: /showOneProject/{id}
    defaults: { _controller: MBLBundle:User:showOneProject }

showMyProject:
    path: /showMyProject
    defaults: { _controller: MBLBundle:User:showMyProject }

deleteMyProject:
    path: /deleteMyProject/{id}
    defaults: { _controller: MBLBundle:User:deleteMyProject }


testTraduction:
    path: /test/{name}
    defaults: { _controller: MBLBundle:User:traduction }





# Cette route doit rester la dernière
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MBLBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

chatIndex:
    path: /chatIndex/{id}
    defaults:
        _controller: MBLBundle:User:chatIndex
        id: null


chatConnect:
    path: /chatConnect/{id}
    defaults: { _controller: MBLBundle:User:chatConnect}
    methods: GET

connect:
    path: /connect/{id}
    defaults:
        _controller: MBLBundle:User:connect
        id: null


chatDisconnect:
    path: /chatDisconnect/{id}
    defaults: { _controller: MBLBundle:User:chatDisconnect}
    methods: GET

# Cette route doit rester la dernière
#remove_trailing_slash:
#    path: /{url}
#    defaults: { _controller: MBLBundle:Redirecting:removeTrailingSlash }
#    requirements:
#        url: .*/$
#    methods: [GET]





