mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:User:index }

admin:
    resource: "@MBLBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

user:
    resource: "@MBLBundle/Resources/config/routing/user.yml"
    prefix:   /
