mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:User:index }

homepageProfil:
    path: /homepageProfil
    defaults: { _controller: MBLBundle:User:homepageProfil }

editProfil:
    path: /editProfil
    defaults: { _controller: MBLBundle:User:editProfil }

showProfil:
    path: /showProfil
    defaults: { _controller: MBLBundle:User:showProfil }

createProjet:
    path: /createProject
    defaults: { _controller: MBLBundle:User:createProject }

listProjetsProfil:
    path: /mesProjets
    defaults: { _controller: MBLBundle:User:showProjetsProfil }

editProjet:
    path: /editProject
    defaults: { _controller: MBLBundle:User:editProject }

createProfilRechercheProjet:
    path: /createProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:createProfilRechercheProject
        id: null

showProject:
    path: /showProject
    defaults: { _controller: MBLBundle:User:showProject }



