mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:User:index }

homepageProfil:
    path: /homepageProfil
    defaults: { _controller: MBLBundle:User:homepageProfil }

editProfil:
    path: /editProfil
    defaults: { _controller: MBLBundle:User:editProfil }

showProfil:
    path: /showProfil
    defaults: { _controller: MBLBundle:User:showProfil }

createProfil:
    path: /createProfil
    defaults: { _controller: MBLBundle:User:createProfil }

createProjet:
    path: /createProject
    defaults: { _controller: MBLBundle:User:createProject }

createProfilRechercheProjet:
    path: /createProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:createProfilRechercheProject
        id: null

showProject:
    path: /showProject
    defaults: { _controller: MBLBundle:User:showProject }

showMyProject:
    path: /showMyProject
    defaults: { _controller: MBLBundle:User:showMyProject }



