userHomepage:
    path: /userHomepage
    defaults: { _controller: MBLBundle:User:index }

admin:
    resource: "@MBLBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

user:
    resource: "@MBLBundle/Resources/config/routing_user.yml"
    prefix:   /

