## src/MBLBundle/Resources/config/validation.yml
#MBLBundle\Entity\Projet:
#    properties:
#        bioUrl:
#            - Url: ~
#
#
#MBLBundle\Entity\Profil:
#    properties:
#        bioUrl:
#            - Url: ~
#