## src/MBLBundle/Resources/config/validation.yml

#MBLBundle\Entity\Projet:
#    properties:
#        bioUrl:
#            - Url: { protocols: [http, https] }
#
#
#MBLBundle\Entity\Profil:
#    properties:
#        bioUrl:
#            - Url: { protocols: [http, https] }